### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by andrewc910** [angeljruiz/BridgeAPI.rb#25]
A list of things that need to get done before we are "done" with the backend. Feel free to edit this to add/check off TODO's.

- [ ] Syntax Parsing - Status: In Progress #24 
    - Parse `$env` & `$payload` into their respective values

- [ ] Request Deconstructing - Status: In Progress #24 
    - Remove sensitive headers such as api keys from outbound requests prior to saving

- [ ] EventWorker - Status: In Progress #23 
    - Bridge 2 servers together

- [ ] Deploy - Status: Not Started
   - Will be deployed to EBS

- [ ] Real World Test - Status: Not Started
    - I want us to each set up 2-3 connections and run about 50 total events each. I think 150 events would be a solid test to ensure everything is working as it should.
